version: "1"

services:
  chat_back_app:
    build:
        context: ./backend/
    container_name: chat-back-app
    ports:
      - 8003:8000
    restart: always

  nginx_chat_app:
    image: nginx:latest
    container_name: nginx-chat-app
    ports:
      - 83:80
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-chat.rule=Host(`api-chat.tesseractmaks.tech`)"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  default:
    name: proxynet
    external: true


